apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: b
  name: my-deployment
  labels:
    app: get-started
spec:
  replicas: 2
  selector:
    matchLabels:
      app: get-started
  template:
    metadata:
      labels:
        app: get-started
    spec:
      containers:
      - name: myapp
        image: vplauzon/get-started:part2-no-redis
        ports:
        - containerPort: 80